title: "{ graeme_o }"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a simple blog to experiment Github Pages with Jekyll...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  graemeo

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
